### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by peter-shr** [alexbruy/processing-prepair#1]
Hello,
I tried the plugin today. It went through and ended with this error message:

`2017-10-26T08:37:53	2	Uncaught error while executing algorithm
			Traceback (most recent call last):
			Traceback (most recent call last):|
			File "C:/Users/USER/.qgis2/python/plugins\processing\core\GeoAlgorithm.py", line 227, in execute|
			self.processAlgorithm(progress)| 
			File "C:/Users/USER/.qgis2/python/plugins\processing_prepair\prepair.py", line 131, in processAlgorithm|
			result = prepairUtils.execute(commands, progress)|
			File "C:/Users/USER/.qgis2/python/plugins\processing_prepair\prepairUtils.py", line 53, in execute|
			print fused_command|IOError: [Errno 9] Bad file descriptor|`

System: W10, QGIS 2.18.3

Greeting Peter
(Translated with: www.deepl.com)

**Comment by alexbruy** [comment]
Fixed in 0.5.1
